### ISSUE TITLE
Sorry, I'm working... and nothing else showing up

### ISSUE THREAD

**Issue by s24195** [meltzow/deck-ng#50]
Hi there,

since about two weeks when I am opening the app, all it shows is "Sorry, I'm working..."

Find attached a screenshot.
Let me know, if I can provide more info to debug it.

iOS 16.5 / iPadOS 16.5

![Deck-ng working](https://github.com/meltzow/deck-ng/assets/6176724/baa3397f-24bc-4ca9-8cbd-36e8bd1e6ffa)

**Comment by meltzow** [comment]
Hi,
thank you for your feedback. 
It's looks like, there is something strange at the authentication on your nextcloud server or inside the app. Perhaps the credentials have changed/removed?! To error logging must be better in our app, sorry. 

But perhaps following workaround can help you.  
1. uninstall the app
2. reinstall the app
3. force a new login

please let me know if it's working.

**Comment by s24195** [comment]
Hi,

this did not help.
With the reinstalled app, I am now already stuck at the very initial page, where I only add the URL of my server.

So basically I entered the URL by scanning the QR code, or I typed it in manually and it does not do anything.

What I was able to track down, in my apache error log I find the following:

[Mon Jul 03 07:25:28.940227 2023] [proxy_fcgi:error] [pid 813:tid 140472928454400] [client 'my-reverse-proxy-IP:43770] AH01071: Got error 'Primary script unknown'

My URL is something like cloud.example.com/**nextcloud**

In my access log I can see that you are trying to access 
[03/Jul/2023:07:38:18 +0000] "POST **/index.php/login/v2** HTTP/1.1" 404 219 "-" "App/49 CFNetwork/1408.0.4 Darwin/22.5.0"
but this is  **without** the **nextcloud subdirectory** and furthermore it seems that a login/**v2** is not existing on my server.

Hope this helps. If you need additional info to debug this, please let me know.

BTW, I am also using https://apps.apple.com/de/app/nextcloud-deck/id1570892788 and this app does not have problems (that could show that this is on my server side).

Thank you for your help!

**Comment by meltzow** [comment]
ok, very strange. 
Thanks for analysing the situation. Sorry I feel sad about your problem. I have an idea, what the problem can be, but at this moment I don't have any solution for this.
I will investigate more. 
Sorry for your circumstances ...

**Comment by meltzow** [comment]
Hi,
I acknowledge, there is problem with nextcloud on URL-subpaths like https://example.com/nextcloud
Or better, I hope there was a problem with it. I prepared a test version 1.6.1 of the app. There is a fix in it. I hope so. 
Because I don't have a nextcloud on subpath. 
So I ask you: "Will you be tester for the new app version?" 
If yes, I need a name and a email address from you. So I can register you inside testflight. This is the official testing environment from apple. 
I'm sure you get an email with instructions like "download the testflight app from apple in appstore". Inside there you get my new version of deck ng (1.6.1).

**Comment by s24195** [comment]
Fixed!
The testflight version is working for me.

**Comment by s24195** [comment]
Fixed, works with the testflight version.
